algoritmo " Creuza01"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

var
   ano_atual, ano_nasc, idade: Inteiro

inicio
      Escreva ("Em que ano nos estamos?")
      Leia (ano_atual)
      Escreva("Em que ano eu nasc?")
      Leia (ano_nasc)
      idade <- ano_atual - ano_nasc
      Escreva ("Minha idade sera = ", idade)

fimalgoritmo