algoritmo "exercicio B"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Adonias

var
  numpecas,totdef: inteiro
 percdef: real

inicio
  escreva ("Digite o numero de peças: ")

  leia (numpecas)

  escreva (" Digite o total de peças defeituosas: ")

  leia (totdef)

 se (totdef >numpecas*10/100)entao

  escreva (" maquina precisa de manutenção")

  senao

  escreva (" maquina não precisa de manutenção")

  fimse

fimalgoritmo

