Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Adonias
// Descrição   : exercio 1 aula
// Autor(a)    : Ariosvaldo Durans
// Data atual  : 26/08/2019
Var
// Seção de Declarações das variáveis 
nome: caracter
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Escreva ("informar seu nome:")
    Leia(nome)
    Escreva ("informar sua idade:" )
    leia (idade)

Fimalgoritmo