Algoritmo "semnome"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor: Adonias
// Descrição: exercício 1 aula
// Autor (a): Ariosvaldo Durans
// Data atual: 26/08/2019
Var
// Seção de declarações das variáveis
nome: caracter
idade: inteiro

Inicio
// Seção de Comandos, Procedimentos, Funções, Operadores, etc ...
    Escreva ("informe seu nome:")
    Leia (nome)
    Escreva ("informar sua idade:")
    leia (idade)

Fimalgoritmo