Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Adonias
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Ary
// Data atual  : 26/08/2019
Var
// Seção de Declarações das variáveis 
numero, dobro:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("digite um numero:")
leia (numero)
dobro <-numero * 2
Escreva(" o dobro do numero é: " ,dobro )

Fimalgoritmo